### ISSUE TITLE
Gazebo 

### ISSUE THREAD

**Issue by hsaleem1** [slamcore/follow_waypoints#1]
Hi @bergercookie,

I have cloned to the repository and launched the follow_waypoints by using the command "roslaunch follow_waypoints follow_waypoints.launch". I got the following output: 

process[dynparam_Ubuntu_14007_4263002704199055716-2]: started with pid [14025]
[INFO] [1638600216.207114]: Connecting to move_base...
[dynparam_Ubuntu_14007_4263002704199055716-2] process has finished cleanly
log file: /home/user/.ros/log/803124a0-54ba-11ec-a955-c025e9292bff/dynparam_IT075882_Ubuntu_14007_4263002704199055716-2*.log

Could you please guide me how can I get the gazebo output after that?
Thanks for the help.

**Comment by bergercookie** [comment]
Hi there,

I 'm not sure what you are trying to accomplish to be honest.

Have you also executed `move_base` alongside `follow_waypoints.launch`? This package works by sending goals to move_base, then querying it for the latest position and sending new goals when the robot is within reach of the already followed goal.

**Comment by bergercookie** [comment]
Hi @hsaleem1, I'll close this one for now. Feel free to respond though  and we can potentially reopen this.
