### ISSUE TITLE
No response when sending path_ready trigger?

### ISSUE THREAD

**Issue by CJdev99** [slamcore/follow_waypoints#2]
I have used Rviz to successfully navigate my robot from A to B with nav goals. Added this package to my project and it confirms that move_base is connected & I successfully add queue of waypoints, but when I send the /path_ready -1 trigger, there is no response. Any idea why there is no response to the trigger?

**Comment by nikoskoukis-slamcore** [comment]
Hi @CJdev99 ,

Sorry for the late reply, is this still an issue for you?
We have not seen this issue come up AFAIR.

For now I'll close the issue. If this persists though feel free to come up with a bit more information (output of `rosservice list`, `rosnode list`, etc.) and we can investigate.
